# Generated by Django 4.1.3 on 2023-01-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglink',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reglink', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
