# Generated by Django 4.1.3 on 2023-01-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reglink_delete_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reglink',
            old_name='reglink',
            new_name='reglinka',
        ),
    ]
