# Generated by Django 4.1.3 on 2023-01-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_reglink_reglink_reglinka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reglink',
            old_name='reglinka',
            new_name='reglink',
        ),
    ]
